services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - dev-hello
#    volumes:
#      - logs:/logs # Ensure this matches the path where logs are mounted in other services

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.2
    container_name: logstash
    volumes:
      - ./logs:/usr/share/logstash/logs
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
#      - ./logs:/usr/share/logstash/log
    ports:
      - "5044:5044"
      - "9600:9600"
    networks:
      - dev-hello
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - dev-hello
    depends_on:
      - elasticsearch

  helloworld:
    build: .
    image: hello-world-app
    container_name: hello-world
    ports:
      - "3400:3400"
    networks:
      - dev-hello
    volumes:
      - ./logs:/app/logs
#    volumes:
#      - ./logs:/usr/hello-world/app/logs  # This must match the volume mount in other services

networks:
  dev-hello:
    driver: bridge

